const DChart = {
  liberally: {
    Vegetables: [
      {
        Name: 'Ash gourd',
        'Energy (Kcal)': 17.45,
        'CHO (gm)': 2.84,
        'Protein (gm)': 0.79,
        'Total Fat (gm)': 0.14,
        'Total  Fiber (gm)': 3.37,
        'Glycemic Index': 'Nil',
        img: 'ashgourd.jpeg',
      },
      {
        Name: 'Bittergourd',
        'Energy (Kcal)': 19.36,
        'CHO (gm)': 2.29,
        'Protein (gm)': 1.61,
        'Total Fat (gm)': 0.26,
        'Total  Fiber (gm)': 3.72,
        'Glycemic Index': 'Nil',
        img: 'bittergourd.png',
      },
      {
        Name: 'Bottlegourd',
        'Energy (Kcal)': 12.91,
        'CHO (gm)': 2.25,
        'Protein (gm)': 0.49,
        'Total Fat (gm)': 0.13,
        'Total  Fiber (gm)': 2.11,
        'Glycemic Index': 'Nil',
        img: 'bottlegourd1.jpg',
      },
      {
        Name: 'Brinjal',
        'Energy (Kcal)': 25.33,
        'CHO (gm)': 3.52,
        'Protein (gm)': 1.48,
        'Total Fat (gm)': 0.32,
        'Total  Fiber (gm)': 3.98,
        'Glycemic Index': 'Nil',
        img: 'brinjal.jpg',
      },
      {
        Name: 'Cho-cho-marrow',
        'Energy (Kcal)': 18.88,
        'CHO (gm)': 3.47,
        'Protein (gm)': 0.66,
        'Total Fat (gm)': 0.15,
        'Total  Fiber (gm)': 1.55,
        'Glycemic Index': 'Nil',
        img: 'cho-cho-marrow.png',
      },
      {
        Name: 'Knol-Khol',
        'Energy (Kcal)': 42.54,
        'CHO (gm)': 6.16,
        'Protein (gm)': 3.12,
        'Total Fat (gm)': 0.35,
        'Total  Fiber (gm)': 2.76,
        'Glycemic Index': 'Nil',
        img: 'knolkhol.png',
      },
      {
        Name: 'Kovai (Ivy gourd)',
        'Energy (Kcal)': 19.12,
        'CHO (gm)': 2.41,
        'Protein (gm)': 1.22,
        'Total Fat (gm)': 0.24,
        'Total  Fiber (gm)': 3.25,
        'Glycemic Index': 'Nil',
        img: 'kovai(ivygourd).png',
      },
      {
        Name: 'Ladys finger',
        'Energy (Kcal)': 27.49,
        'CHO (gm)': 3.62,
        'Protein (gm)': 2.08,
        'Total Fat (gm)': 0.22,
        'Total  Fiber (gm)': 4.08,
        'Glycemic Index': 'Nil',
        img: "lady'sfinger.png",
      },
      {
        Name: 'Ridge gourd',
        'Energy (Kcal)': 13.15,
        'CHO (gm)': 1.72,
        'Protein (gm)': 0.91,
        'Total Fat (gm)': 1.2,
        'Total  Fiber (gm)': 0.14,
        'Glycemic Index': 'Nil',
        img: 'ridgegourd.png',
      },
      {
        Name: 'Snake gourd',
        'Energy (Kcal)': 11.95,
        'CHO (gm)': 1.23,
        'Protein (gm)': 0.89,
        'Total Fat (gm)': 0.25,
        'Total  Fiber (gm)': 2.27,
        'Glycemic Index': 'Nil',
        img: 'snakegourd.png',
      },
      {
        Name: 'Banana flower',
        'Energy (Kcal)': 21.27,
        'CHO (gm)': 2.15,
        'Protein (gm)': 1.47,
        'Total Fat (gm)': 0.63,
        'Total  Fiber (gm)': 5.25,
        'Glycemic Index': 'Nil',
        img: 'bananaflower.jpeg',
      },
      {
        Name: 'Banana stem',
        'Energy (Kcal)': 39.44,
        'CHO (gm)': 8.64,
        'Protein (gm)': 0.35,
        'Total Fat (gm)': 0.16,
        'Total  Fiber (gm)': 2.12,
        'Glycemic Index': 'Nil',
        img: 'bananastem.png',
      },
      {
        Name: 'Tomato',
        'Energy (Kcal)': 19.6,
        'CHO (gm)': 2.71,
        'Protein (gm)': 0.9,
        'Total Fat (gm)': 0.47,
        'Total  Fiber (gm)': 1.77,
        'Glycemic Index': 15,
        img: 'tomato.png',
      },
    ],
    'Pulses and Legumes': [
      {
        Name: 'Broad beans',
        'Energy (Kcal)': 29.4,
        'CHO (gm)': 2.11,
        'Protein (gm)': 3.85,
        'Total Fat (gm)': 0.15,
        'Total  Fiber (gm)': 8.63,
        'Glycemic Index': 'Nil',
        img: 'indianbroadbeans.png',
      },
      {
        Name: 'Cluster Beans',
        'Energy (Kcal)': 40.15,
        'CHO (gm)': 4.91,
        'Protein (gm)': 3.55,
        'Total Fat (gm)': 0.37,
        'Total  Fiber (gm)': 4.83,
        'Glycemic Index': 'Nil',
        img: 'clusterbeans.png',
      },
      {
        Name: 'French Beans',
        'Energy (Kcal)': 24.38,
        'CHO (gm)': 2.68,
        'Protein (gm)': 2.49,
        'Total Fat (gm)': 0.26,
        'Total  Fiber (gm)': 4.38,
        'Glycemic Index': 'Nil',
        img: 'frenchbeans.jpg',
      },
    ],
    'Greenleafy Vegetables': [
      {
        Name: 'Agathi leaves',
        'Energy (Kcal)': 70.51,
        'CHO (gm)': 5.21,
        'Protein (gm)': 8.01,
        'Total Fat (gm)': 1.35,
        'Total  Fiber (gm)': 8.6,
        'Glycemic Index': 'Nil',
        img: 'agathileaves.jpg',
      },
      {
        Name: 'Amaranth leaves',
        'Energy (Kcal)': 30.59,
        'CHO (gm)': 2.28,
        'Protein (gm)': 3.29,
        'Total Fat (gm)': 0.65,
        'Total  Fiber (gm)': 4.41,
        'Glycemic Index': 'Nil',
        img: 'amaranthleaves.jpg',
      },
      {
        Name: 'Cabbage green',
        'Energy (Kcal)': 30.11,
        'CHO (gm)': 2.79,
        'Protein (gm)': 3.63,
        'Total Fat (gm)': 0.13,
        'Total  Fiber (gm)': 2.01,
        'Glycemic Index': 10,
        img: 'cabbagegreen.png',
      },
      {
        Name: 'Cauliflower leaves',
        'Energy (Kcal)': 35.37,
        'CHO (gm)': 3.39,
        'Protein (gm)': 3.9,
        'Total Fat (gm)': 0.42,
        'Total  Fiber (gm)': 3.43,
        'Glycemic Index': 6,
        img: 'cauliflowerleaves.png',
      },
      {
        Name: 'Corriander leaves',
        'Energy (Kcal)': 31.07,
        'CHO (gm)': 1.93,
        'Protein (gm)': 3.52,
        'Total Fat (gm)': 0.7,
        'Total  Fiber (gm)': 4.66,
        'Glycemic Index': 'Nil',
        img: 'corrianderleaves.png',
      },
      {
        Name: 'Curry leaves',
        'Energy (Kcal)': 63.58,
        'CHO (gm)': 4.51,
        'Protein (gm)': 7.41,
        'Total Fat (gm)': 1.06,
        'Total  Fiber (gm)': 16.83,
        'Glycemic Index': 'Nil',
        img: 'curryleaves.png',
      },
      {
        Name: 'Fenugreek leaves',
        'Energy (Kcal)': 34.42,
        'CHO (gm)': 2.17,
        'Protein (gm)': 3.68,
        'Total Fat (gm)': 0.83,
        'Total  Fiber (gm)': 4.9,
        'Glycemic Index': 'Nil',
        img: 'fenugreekleaves.png',
      },
      {
        Name: 'Lettuce',
        'Energy (Kcal)': 21.75,
        'CHO (gm)': 3.01,
        'Protein (gm)': 1.54,
        'Total Fat (gm)': 0.27,
        'Total  Fiber (gm)': 1.79,
        'Glycemic Index': 7,
        img: 'lettuce.png',
      },
      {
        Name: 'Mint leaves',
        'Energy (Kcal)': 37.05,
        'CHO (gm)': 2.39,
        'Protein (gm)': 4.66,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 5.89,
        'Glycemic Index': 'Nil',
        img: 'mintleaves.jpg',
      },
      {
        Name: 'Mustard leaves',
        'Energy (Kcal)': 30.35,
        'CHO (gm)': 2.41,
        'Protein (gm)': 3.52,
        'Total Fat (gm)': 0.51,
        'Total  Fiber (gm)': 3.92,
        'Glycemic Index': 'Nil',
        img: 'mustardleaves.jpg',
      },
      {
        Name: 'Ponnaganni',
        'Energy (Kcal)': 50.91,
        'CHO (gm)': 5.17,
        'Protein (gm)': 5.29,
        'Total Fat (gm)': 0.71,
        'Total  Fiber (gm)': 6.74,
        'Glycemic Index': 'Nil',
        img: 'ponnanganileaves.png',
      },
      {
        Name: 'Radish leaves',
        'Energy (Kcal)': 26.05,
        'CHO (gm)': 2.77,
        'Protein (gm)': 2.22,
        'Total Fat (gm)': 0.51,
        'Total  Fiber (gm)': 1.82,
        'Glycemic Index': 'Nil',
        img: 'radishleaves.png',
      },
      {
        Name: 'Spinach',
        'Energy (Kcal)': 24.38,
        'CHO (gm)': 2.05,
        'Protein (gm)': 2.14,
        'Total Fat (gm)': 0.64,
        'Total  Fiber (gm)': 2.38,
        'Glycemic Index': 12,
        img: 'spinach.jpg',
      },
    ],
    Spices: [
      {
        Name: 'Cardamom',
        'Energy (Kcal)': 270.55,
        'CHO (gm)': 52.53,
        'Protein (gm)': 6.69,
        'Total Fat (gm)': 2.8,
        'Total  Fiber (gm)': 23.46,
        'Glycemic Index': 'Nil',
        img: 'cardamom.png',
      },
      {
        Name: 'Cinnamon',
        'Energy (Kcal)': 247,
        'CHO (gm)': 80.59,
        'Protein (gm)': 3.99,
        'Total Fat (gm)': 1.24,
        'Total  Fiber (gm)': 53.1,
        'Glycemic Index': 'Nil',
        img: 'cinnamon.png',
      },
      {
        Name: 'Cumin',
        'Energy (Kcal)': 304.49,
        'CHO (gm)': 22.62,
        'Protein (gm)': 13.91,
        'Total Fat (gm)': 16.64,
        'Total  Fiber (gm)': 30.35,
        'Glycemic Index': 'Nil',
        img: 'cumin.png',
      },
      {
        Name: 'Fenugreek',
        'Energy (Kcal)': 234.94,
        'CHO (gm)': 10.57,
        'Protein (gm)': 25.41,
        'Total Fat (gm)': 5.72,
        'Total  Fiber (gm)': 47.55,
        'Glycemic Index': 'Nil',
        img: 'fenugreek.png',
      },
      {
        Name: 'Turmeric Powder',
        'Energy (Kcal)': 280.59,
        'CHO (gm)': 49.22,
        'Protein (gm)': 7.66,
        'Total Fat (gm)': 5.03,
        'Total  Fiber (gm)': 21.38,
        'Glycemic Index': 'Nil',
        img: 'turmericpowder.png',
      },
    ],
  },
  moderately: {
    'Cereals and Millets': [
      {
        Name: 'Black rice',
        'Energy (Kcal)': 355.56,
        'CHO (gm)': 75.56,
        'Protein (gm)': 8.89,
        'Total Fat (gm)': 3.33,
        'Total  Fiber (gm)': 2.2,
        'Glycemic Index': 'Nil',
        img: 'blackrice.jpeg',
      },
      {
        Name: 'Brown Rice',
        'Energy (Kcal)': 353.73,
        'CHO (gm)': 74.8,
        'Protein (gm)': 9.16,
        'Total Fat (gm)': 1.24,
        'Total  Fiber (gm)': 4.43,
        'Glycemic Index': '68±4',
        img: 'brownrice.jpeg',
      },
      {
        Name: 'Barley',
        'Energy (Kcal)': 315.73,
        'CHO (gm)': 61.29,
        'Protein (gm)': 10.94,
        'Total Fat (gm)': 1.3,
        'Total  Fiber (gm)': 15.64,
        'Glycemic Index': '28±2',
        img: 'barley.jpg',
      },
      {
        Name: 'Parboiled rice',
        'Energy (Kcal)': 351.58,
        'CHO (gm)': 77.16,
        'Protein (gm)': 7.81,
        'Total Fat (gm)': 0.55,
        'Total  Fiber (gm)': 3.74,
        'Glycemic Index': '73±4',
        img: 'parboiledrice.jpg',
      },
      {
        Name: 'Milled raw rice',
        'Energy (Kcal)': 356.36,
        'CHO (gm)': 78.24,
        'Protein (gm)': 7.94,
        'Total Fat (gm)': 0.52,
        'Total  Fiber (gm)': 2.81,
        'Glycemic Index': 'Nil',
        img: 'milledrawrice.png',
      },
      {
        Name: 'Bajra',
        'Energy (Kcal)': 347.99,
        'CHO (gm)': 61.78,
        'Protein (gm)': 10.96,
        'Total Fat (gm)': 5.43,
        'Total  Fiber (gm)': 11.49,
        'Glycemic Index': 49,
        img: 'bajra.jpeg',
      },
      {
        Name: 'Jowar',
        'Energy (Kcal)': 334.13,
        'CHO (gm)': 67.68,
        'Protein (gm)': 9.97,
        'Total Fat (gm)': 1.73,
        'Total  Fiber (gm)': 10.22,
        'Glycemic Index': 'Nil',
        img: 'jowar.png',
      },
      {
        Name: 'Ragi',
        'Energy (Kcal)': 320.75,
        'CHO (gm)': 66.82,
        'Protein (gm)': 7.16,
        'Total Fat (gm)': 1.92,
        'Total  Fiber (gm)': 11.18,
        'Glycemic Index': 'Nil',
        img: 'ragi.png',
      },
      {
        Name: 'Samai',
        'Energy (Kcal)': 346.32,
        'CHO (gm)': 65.55,
        'Protein (gm)': 10.13,
        'Total Fat (gm)': 3.89,
        'Total  Fiber (gm)': 7.72,
        'Glycemic Index': 'Nil',
        img: 'samai.png',
      },
      {
        Name: 'Varagu',
        'Energy (Kcal)': 331.74,
        'CHO (gm)': 66.19,
        'Protein (gm)': 8.92,
        'Total Fat (gm)': 2.55,
        'Total  Fiber (gm)': 6.39,
        'Glycemic Index': 'Nil',
        img: 'varagu.jpeg',
      },
      {
        Name: 'Wheat',
        'Energy (Kcal)': 321.94,
        'CHO (gm)': 64.72,
        'Protein (gm)': 10.59,
        'Total Fat (gm)': 1.47,
        'Total  Fiber (gm)': 11.23,
        'Glycemic Index': 'Nil',
        img: 'wheat.png',
      },
    ],
    'Pulses and Legumes': [
      {
        Name: 'Black gram dhal',
        'Energy (Kcal)': 324.09,
        'CHO (gm)': 51,
        'Protein (gm)': 23.06,
        'Total Fat (gm)': 1.69,
        'Total  Fiber (gm)': 11.93,
        'Glycemic Index': 'Nil',
        img: 'blackgramdhal.png',
      },
      {
        Name: 'Black gram,Whole ',
        'Energy (Kcal)': 291.35,
        'CHO (gm)': 43.99,
        'Protein (gm)': 21.97,
        'Total Fat (gm)': 1.58,
        'Total  Fiber (gm)': 20.41,
        'Glycemic Index': 'Nil',
        img: 'blackgramwhole.png',
      },
      {
        Name: 'Bengal gram dhal',
        'Energy (Kcal)': 287.05,
        'CHO (gm)': 39.56,
        'Protein (gm)': 18.77,
        'Total Fat (gm)': 5.11,
        'Total  Fiber (gm)': 25.33,
        'Glycemic Index': 'Nil',
        img: 'bengalgramdhal.jpg',
      },
      {
        Name: 'Bengal gram,Whole (Brown Chickpea)',
        'Energy (Kcal)': 287.05,
        'CHO (gm)': 39.56,
        'Protein (gm)': 18.77,
        'Total Fat (gm)': 5.11,
        'Total  Fiber (gm)': 25.33,
        'Glycemic Index': 'Nil',
        img: 'bengalgramwholebrown(brownchickpea).jpg',
      },
      {
        Name: 'Cowpea,Brown',
        'Energy (Kcal)': 320.27,
        'CHO (gm)': 54.62,
        'Protein (gm)': 20.36,
        'Total Fat (gm)': 1.15,
        'Total  Fiber (gm)': 11.54,
        'Glycemic Index': 'Nil',
        img: 'cowpea,brown.png',
      },
      {
        Name: 'Green gram,Whole',
        'Energy (Kcal)': 293.74,
        'CHO (gm)': 46.13,
        'Protein (gm)': 22.53,
        'Total Fat (gm)': 1.14,
        'Total  Fiber (gm)': 17.04,
        'Glycemic Index': '38±1',
        img: 'greengram,whole.jpg',
      },
      {
        Name: 'Green gram dhal',
        'Energy (Kcal)': 325.76,
        'CHO (gm)': 52.59,
        'Protein (gm)': 23.88,
        'Total Fat (gm)': 1.35,
        'Total  Fiber (gm)': 9.37,
        'Glycemic Index': 'Nil',
        img: 'greengramdhal.jpg',
      },
      {
        Name: 'Kidney beans',
        'Energy (Kcal)': 299.24,
        'CHO (gm)': 48.61,
        'Protein (gm)': 19.91,
        'Total Fat (gm)': 1.77,
        'Total  Fiber (gm)': 16.57,
        'Glycemic Index': '70±11',
        img: 'kidneybeans.png',
      },
      {
        Name: 'Red gram dhal',
        'Energy (Kcal)': 330.78,
        'CHO (gm)': 55.23,
        'Protein (gm)': 21.7,
        'Total Fat (gm)': 1.56,
        'Total  Fiber (gm)': 9.06,
        'Glycemic Index': 36,
        img: 'redgramdhal.png',
      },
      {
        Name: 'Soya beans,white',
        'Energy (Kcal)': 377.39,
        'CHO (gm)': 10.16,
        'Protein (gm)': 37.8,
        'Total Fat (gm)': 19.42,
        'Total  Fiber (gm)': 22.63,
        'Glycemic Index': '16±1',
        img: 'soyabeanswhite.jpg',
      },
      {
        Name: 'Lentils, yellow',
        'Energy (Kcal)': 297.8,
        'CHO (gm)': 47.91,
        'Protein (gm)': 22.87,
        'Total Fat (gm)': 0.61,
        'Total  Fiber (gm)': 16.66,
        'Glycemic Index': '32±5',
        img: 'lentils,yellow.png',
      },
    ],
    Fruits: [
      {
        Name: 'Apple,Big',
        'Energy (Kcal)': 62.64,
        'CHO (gm)': 13.11,
        'Protein (gm)': 0.29,
        'Total Fat (gm)': 0.64,
        'Total  Fiber (gm)': 2.59,
        'Glycemic Index': '36±2',
        img: 'apple.jpg',
      },
      {
        Name: 'Avocado',
        'Energy (Kcal)': 144.36,
        'CHO (gm)': 1.75,
        'Protein (gm)': 2.95,
        'Total Fat (gm)': 13.86,
        'Total  Fiber (gm)': 6.69,
        'Glycemic Index': 'Nil',
        img: 'avocado.png',
      },
      {
        Name: 'Blueberries',
        'Energy (Kcal)': 57,
        'CHO (gm)': 14.49,
        'Protein (gm)': 0.74,
        'Total Fat (gm)': 0.33,
        'Total  Fiber (gm)': 2.4,
        'Glycemic Index': 53,
        img: 'blueberries.png',
      },
      {
        Name: 'Cantaloupe',
        'Energy (Kcal)': 23.18,
        'CHO (gm)': 4.24,
        'Protein (gm)': 9.8,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 1.51,
        'Glycemic Index': 70,
        img: 'cantaloupe.png',
      },
      {
        Name: 'Guava,pink',
        'Energy (Kcal)': 46.61,
        'CHO (gm)': 9.14,
        'Protein (gm)': 1.19,
        'Total Fat (gm)': 0.25,
        'Total  Fiber (gm)': 7.39,
        'Glycemic Index': 29,
        img: 'guava,pink.png',
      },
      {
        Name: 'Guava,white',
        'Energy (Kcal)': 32.27,
        'CHO (gm)': 5.13,
        'Protein (gm)': 1.44,
        'Total Fat (gm)': 0.32,
        'Total  Fiber (gm)': 8.59,
        'Glycemic Index': 'Nil',
        img: 'guava,white.png',
      },
      {
        Name: 'Gooseberry',
        'Energy (Kcal)': 23.66,
        'CHO (gm)': 4.39,
        'Protein (gm)': 0.34,
        'Total Fat (gm)': 0.16,
        'Total  Fiber (gm)': 7.75,
        'Glycemic Index': 'Nil',
        img: 'gooseberry.png',
      },
      {
        Name: 'Jamun',
        'Energy (Kcal)': 54.25,
        'CHO (gm)': 10.64,
        'Protein (gm)': 0.92,
        'Total Fat (gm)': 0.63,
        'Total  Fiber (gm)': 4.35,
        'Glycemic Index': 43,
        img: 'jamunfruit.jpeg',
      },
      {
        Name: 'Lemon',
        'Energy (Kcal)': 57,
        'CHO (gm)': 11.1,
        'Protein (gm)': 1,
        'Total Fat (gm)': 0.9,
        'Total  Fiber (gm)': 1.7,
        'Glycemic Index': 'Nil',
        img: 'lemon.jpg',
      },
      {
        Name: 'Mosambi',
        'Energy (Kcal)': 27.25,
        'CHO (gm)': 5.18,
        'Protein (gm)': 0.76,
        'Total Fat (gm)': 0.2,
        'Total  Fiber (gm)': 2.07,
        'Glycemic Index': 'Nil',
        img: 'mosambi.png',
      },
      {
        Name: 'Oranges',
        'Energy (Kcal)': 37.28,
        'CHO (gm)': 7.92,
        'Protein (gm)': 19.52,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 1.29,
        'Glycemic Index': '43±3',
        img: 'oranges.png',
      },
      {
        Name: 'Pear',
        'Energy (Kcal)': 37.52,
        'CHO (gm)': 8.09,
        'Protein (gm)': 6.55,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 4.48,
        'Glycemic Index': 33,
        img: 'pear.png',
      },
      {
        Name: 'Pomegranate',
        'Energy (Kcal)': 54.73,
        'CHO (gm)': 11.58,
        'Protein (gm)': 1.33,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 2.83,
        'Glycemic Index': 'Nil',
        img: 'pomegranate.jpg',
      },
      {
        Name: 'Peach',
        'Energy (Kcal)': 40.15,
        'CHO (gm)': 7.82,
        'Protein (gm)': 6.98,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 2.13,
        'Glycemic Index': 28,
        img: 'peach.png',
      },
      {
        Name: 'Plum',
        'Energy (Kcal)': 56.88,
        'CHO (gm)': 12.1,
        'Protein (gm)': 0.64,
        'Total Fat (gm)': 0.4,
        'Total  Fiber (gm)': 2.07,
        'Glycemic Index': 69,
        img: 'plum.png',
      },
      {
        Name: 'Papaya',
        'Energy (Kcal)': 23.9,
        'CHO (gm)': 4.61,
        'Protein (gm)': 15.02,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 2.83,
        'Glycemic Index': '60±16',
        img: 'papaya.png',
      },
      {
        Name: 'Strawberries',
        'Energy (Kcal)': 24.62,
        'CHO (gm)': 3.4,
        'Protein (gm)': 15.28,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 2.5,
        'Glycemic Index': 40,
        img: 'strawberries.jpg',
      },
      {
        Name: 'Watermelon',
        'Energy (Kcal)': 16.73,
        'CHO (gm)': 3.02,
        'Protein (gm)': 0.59,
        'Total Fat (gm)': 0.16,
        'Total  Fiber (gm)': 0.78,
        'Glycemic Index': '76±4',
        img: 'watermelon.jpg',
      },
    ],
    'Roots and Tubers': [
      {
        Name: 'Carrot,Raw',
        'Energy (Kcal)': 33.22,
        'CHO (gm)': 5.55,
        'Protein (gm)': 0.95,
        'Total Fat (gm)': 0.47,
        'Total  Fiber (gm)': 4.18,
        'Glycemic Index': 'Nil',
        img: 'carrot.jpg',
      },
      {
        Name: 'Garlic,Big Clove',
        'Energy (Kcal)': 123.8,
        'CHO (gm)': 21.93,
        'Protein (gm)': 6.92,
        'Total Fat (gm)': 0.16,
        'Total  Fiber (gm)': 5.22,
        'Glycemic Index': 'Nil',
        img: 'garlic,bigclove.png',
      },
      {
        Name: 'Garlic,Small Clove',
        'Energy (Kcal)': 122.85,
        'CHO (gm)': 21.84,
        'Protein (gm)': 6.75,
        'Total Fat (gm)': 0.14,
        'Total  Fiber (gm)': 5.47,
        'Glycemic Index': 'Nil',
        img: 'garlic,smallclove.png',
      },
      {
        Name: 'Ginger',
        'Energy (Kcal)': 54.97,
        'CHO (gm)': 8.97,
        'Protein (gm)': 2.22,
        'Total Fat (gm)': 0.85,
        'Total  Fiber (gm)': 5.36,
        'Glycemic Index': 'Nil',
        img: 'ginger.jpg',
      },
      {
        Name: 'Radish',
        'Energy (Kcal)': 32.27,
        'CHO (gm)': 6.56,
        'Protein (gm)': 0.77,
        'Total Fat (gm)': 0.5,
        'Total  Fiber (gm)': 2.65,
        'Glycemic Index': 'Nil',
        img: 'radish.jpg',
      },
      {
        Name: 'Turnip',
        'Energy (Kcal)': 28,
        'CHO (gm)': 6.43,
        'Protein (gm)': 0.9,
        'Total Fat (gm)': 0.1,
        'Total  Fiber (gm)': 1.8,
        'Glycemic Index': 'Nil',
        img: 'turnip.jpg',
      },
    ],
    'Milk and Milk Products': [
      {
        Name: 'Milk,Cow',
        'Energy (Kcal)': 72.9,
        'CHO (gm)': 4.94,
        'Protein (gm)': 3.26,
        'Total Fat (gm)': 4.48,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': '39±3',
        img: 'milk,cow.png',
      },
      {
        Name: 'Skimmed milk',
        'Energy (Kcal)': 34,
        'CHO (gm)': 4.89,
        'Protein (gm)': 3.37,
        'Total Fat (gm)': 0.08,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': '37±4',
        img: 'skimmedmilk.png',
      },
      {
        Name: 'Buttermilk',
        'Energy (Kcal)': 62,
        'CHO (gm)': 4.88,
        'Protein (gm)': 3.21,
        'Total Fat (gm)': 3.31,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'buttermilk.jpg',
      },
      {
        Name: 'Curd',
        'Energy (Kcal)': 60,
        'CHO (gm)': 3,
        'Protein (gm)': 3.1,
        'Total Fat (gm)': 4,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'curd.png',
      },
      {
        Name: 'Yoghurt',
        'Energy (Kcal)': 59,
        'CHO (gm)': 5.4,
        'Protein (gm)': 3.2,
        'Total Fat (gm)': 2.6,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': '41±2',
        img: 'yoghurt.png',
      },
      {
        Name: 'Paneer',
        'Energy (Kcal)': 257.89,
        'CHO (gm)': 12.41,
        'Protein (gm)': 18.86,
        'Total Fat (gm)': 14.78,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'paneer.jpg',
      },
      {
        Name: 'Skimmed milk powder',
        'Energy (Kcal)': 357,
        'CHO (gm)': 51,
        'Protein (gm)': 38,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'skimmedmilkpowder.jpg',
      },
    ],
    'Fish, Egg, Poultry and Meat': [
      {
        Name: 'Tuna fish',
        'Energy (Kcal)': 112.33,
        'CHO (gm)': 0,
        'Protein (gm)': 24.5,
        'Total Fat (gm)': 1.44,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'tuna.jpg',
      },
      {
        Name: 'Sardine fish',
        'Energy (Kcal)': 152.25,
        'CHO (gm)': 0,
        'Protein (gm)': 17.91,
        'Total Fat (gm)': 8.99,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'sardine.jpg',
      },
      {
        Name: 'Salmon',
        'Energy (Kcal)': 172.32,
        'CHO (gm)': 0,
        'Protein (gm)': 20.97,
        'Total Fat (gm)': 9.86,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'salmon.jpg',
      },
      {
        Name: 'Pomfret, black',
        'Energy (Kcal)': 123.09,
        'CHO (gm)': 0,
        'Protein (gm)': 18.91,
        'Total Fat (gm)': 4.83,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'pomfret-black.jpg',
      },
      {
        Name: 'Prawns,small',
        'Energy (Kcal)': 70.98,
        'CHO (gm)': 0,
        'Protein (gm)': 13.07,
        'Total Fat (gm)': 0.78,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'smallprawn.jpg',
      },
      {
        Name: 'Crab,sea',
        'Energy (Kcal)': 81.98,
        'CHO (gm)': 0,
        'Protein (gm)': 10.23,
        'Total Fat (gm)': 1.41,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'crab,sea.png',
      },
      {
        Name: 'Egg, Broiler Hen',
        'Energy (Kcal)': 134.92,
        'CHO (gm)': 0,
        'Protein (gm)': 13.28,
        'Total Fat (gm)': 9.15,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'broileregg.jpg',
      },
      {
        Name: 'Egg,Country Hen',
        'Energy (Kcal)': 168.26,
        'CHO (gm)': 0,
        'Protein (gm)': 13.14,
        'Total Fat (gm)': 13,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'countryegg.jpg',
      },
      {
        Name: 'Chicken, Breast,skinless',
        'Energy (Kcal)': 168.26,
        'CHO (gm)': 0,
        'Protein (gm)': 21.81,
        'Total Fat (gm)': 9,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'chicken,breast,skinless.png',
      },
      {
        Name: 'Chicken, Leg,with skinless',
        'Energy (Kcal)': 383.6,
        'CHO (gm)': 0,
        'Protein (gm)': 19.44,
        'Total Fat (gm)': 12.64,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'chicken,leg,withskinless.png',
      },
      {
        Name: 'Chicken, Thigh,with skinless',
        'Energy (Kcal)': 199.81,
        'CHO (gm)': 0,
        'Protein (gm)': 18.18,
        'Total Fat (gm)': 14.23,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'chicken,thigh,withskinless.png',
      },
      {
        Name: 'Chicken, Wing,with skinless',
        'Energy (Kcal)': 192.88,
        'CHO (gm)': 0,
        'Protein (gm)': 17.42,
        'Total Fat (gm)': 13.81,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'chicken,wing,withskinless.jpg',
      },
      {
        Name: 'Goat Meat ,Lean',
        'Energy (Kcal)': 118,
        'CHO (gm)': 0,
        'Protein (gm)': 21.4,
        'Total Fat (gm)': 3.6,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'goatmeat,lean.jpeg',
      },
      {
        Name: 'Goat Leg',
        'Energy (Kcal)': 159.89,
        'CHO (gm)': 0,
        'Protein (gm)': 22.07,
        'Total Fat (gm)': 7.94,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'goatleg.jpg',
      },
      {
        Name: 'Goat Shoulder',
        'Energy (Kcal)': 188.1,
        'CHO (gm)': 0,
        'Protein (gm)': 20.33,
        'Total Fat (gm)': 11.94,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'goatshoulder.png',
      },
    ],
    'Nuts and Oilseeds': [
      {
        Name: 'Almonds',
        'Energy (Kcal)': 609.23,
        'CHO (gm)': 10.5,
        'Protein (gm)': 20.8,
        'Total Fat (gm)': 58.9,
        'Total  Fiber (gm)': 13.06,
        'Glycemic Index': 'Nil',
        img: 'almonds.jpg',
      },
      {
        Name: 'Coconut',
        'Energy (Kcal)': 408.94,
        'CHO (gm)': 6.3,
        'Protein (gm)': 3.84,
        'Total Fat (gm)': 41.38,
        'Total  Fiber (gm)': 10.42,
        'Glycemic Index': 45,
        img: 'coconut.jpg',
      },
      {
        Name: 'Flaxseeds',
        'Energy (Kcal)': 443.83,
        'CHO (gm)': 10.99,
        'Protein (gm)': 18.55,
        'Total Fat (gm)': 35.67,
        'Total  Fiber (gm)': 26.17,
        'Glycemic Index': 36,
        img: 'flaxseeds.jpg',
      },
      {
        Name: 'Groundnut',
        'Energy (Kcal)': 520.08,
        'CHO (gm)': 17.27,
        'Protein (gm)': 23.65,
        'Total Fat (gm)': 39.63,
        'Total  Fiber (gm)': 10.38,
        'Glycemic Index': 'Nil',
        img: 'groundnuts1.jpeg',
      },
      {
        Name: 'Pumpkin Seeds',
        'Energy (Kcal)': 574,
        'CHO (gm)': 14.71,
        'Protein (gm)': 29.84,
        'Total Fat (gm)': 49.05,
        'Total  Fiber (gm)': 6.5,
        'Glycemic Index': 'Nil',
        img: 'pumpkinseeds.jpeg',
      },
      {
        Name: 'Sesame Seeds,Black',
        'Energy (Kcal)': 507.65,
        'CHO (gm)': 10.29,
        'Protein (gm)': 19.17,
        'Total Fat (gm)': 43.1,
        'Total  Fiber (gm)': 17.16,
        'Glycemic Index': 'Nil',
        img: 'sesameseeds,black.png',
      },
      {
        Name: 'Sesame Seeds,Brown',
        'Energy (Kcal)': 516.49,
        'CHO (gm)': 9.76,
        'Protein (gm)': 21.61,
        'Total Fat (gm)': 43.22,
        'Total  Fiber (gm)': 17.21,
        'Glycemic Index': 'Nil',
        img: 'sesameseeds,brown.png',
      },
      {
        Name: 'Sesame Seeds,White',
        'Energy (Kcal)': 519.6,
        'CHO (gm)': 10.83,
        'Protein (gm)': 21.7,
        'Total Fat (gm)': 43.05,
        'Total  Fiber (gm)': 16.99,
        'Glycemic Index': 'Nil',
        img: 'sesameseeds,white.png',
      },
      {
        Name: 'Sunflower seeds',
        'Energy (Kcal)': 586.28,
        'CHO (gm)': 6.85,
        'Protein (gm)': 23.53,
        'Total Fat (gm)': 51.85,
        'Total  Fiber (gm)': 10.8,
        'Glycemic Index': 'Nil',
        img: 'sunflowerseeds.png',
      },
      {
        Name: 'Walnuts',
        'Energy (Kcal)': 671.37,
        'CHO (gm)': 10.14,
        'Protein (gm)': 14.92,
        'Total Fat (gm)': 64.27,
        'Total  Fiber (gm)': 5.39,
        'Glycemic Index': 15,
        img: 'walnut.jpg',
      },
    ],
    'Fats and Oils': [
      {
        Name: 'Coconut oil',
        'Energy (Kcal)': 895,
        'CHO (gm)': 0.84,
        'Protein (gm)': 0,
        'Total Fat (gm)': 99.1,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'coconutoil.png',
      },
      {
        Name: 'Cooking oil',
        'Energy (Kcal)': 900,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'cookingoil.png',
      },
      {
        Name: 'Cottonseed oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'cottonseedoil.jpg',
      },
      {
        Name: 'Gingelly oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'gingellyoil.png',
      },
      {
        Name: 'Safflower oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'saffloweroil.jpeg',
      },
      {
        Name: 'Soyabean oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'soyabeanoil.png',
      },
      {
        Name: 'Sunflower oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'sunfloweroil.png',
      },
      {
        Name: 'Mustard oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'mustardoil.png',
      },
      {
        Name: 'Olive oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'oliveoil.png',
      },
      {
        Name: 'Ricebran oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'ricebranoil.png',
      },
    ],
  },
  excluded: {
    'Cereals and Millets': [
      {
        Name: 'Cornflakes',
        'Energy (Kcal)': 380,
        'CHO (gm)': 87,
        'Protein (gm)': 6.67,
        'Total Fat (gm)': 1,
        'Total  Fiber (gm)': 2.67,
        'Glycemic Index': '81±6',
        img: 'cornflakes.jpg',
      },
      {
        Name: 'Puffed rice',
        'Energy (Kcal)': 361.85,
        'CHO (gm)': 77.68,
        'Protein (gm)': 7.47,
        'Total Fat (gm)': 1.62,
        'Total  Fiber (gm)': 2.56,
        'Glycemic Index': 'Nil',
        img: 'puffedrice.png',
      },
      {
        Name: 'Instant Oats Porridge',
        'Energy (Kcal)': 374,
        'CHO (gm)': 62.8,
        'Protein (gm)': 13.6,
        'Total Fat (gm)': 7.6,
        'Total  Fiber (gm)': 3.5,
        'Glycemic Index': '79±3',
        img: 'instantoatsporridge.png',
      },
    ],
    Fruits: [
      {
        Name: 'Banana',
        'Energy (Kcal)': 110.66,
        'CHO (gm)': 24.95,
        'Protein (gm)': 1.25,
        'Total Fat (gm)': 0.32,
        'Total  Fiber (gm)': 2.21,
        'Glycemic Index': '51±3',
        img: 'banana.jpg',
      },
      {
        Name: 'Chickoo',
        'Energy (Kcal)': 73.37,
        'CHO (gm)': 13.9,
        'Protein (gm)': 0.92,
        'Total Fat (gm)': 1.26,
        'Total  Fiber (gm)': 9.6,
        'Glycemic Index': 'Nil',
        img: 'chickoo.jpg',
      },
      {
        Name: 'Dates,Processed',
        'Energy (Kcal)': 286.09,
        'CHO (gm)': 67.95,
        'Protein (gm)': 1.18,
        'Total Fat (gm)': 0.41,
        'Total  Fiber (gm)': 6.52,
        'Glycemic Index': 36,
        img: 'dates,processed.jpg',
      },
      {
        Name: 'Grapes,seeded round, black',
        'Energy (Kcal)': 60.71,
        'CHO (gm)': 13.23,
        'Protein (gm)': 0.76,
        'Total Fat (gm)': 0.32,
        'Total  Fiber (gm)': 1.35,
        'Glycemic Index': 59,
        img: 'grapes,seededround,black.jpg',
      },
      {
        Name: 'Jackfruit',
        'Energy (Kcal)': 72.18,
        'CHO (gm)': 14.01,
        'Protein (gm)': 2.74,
        'Total Fat (gm)': 0.15,
        'Total  Fiber (gm)': 3.62,
        'Glycemic Index': 'Nil',
        img: 'jackfruit.png',
      },
      {
        Name: 'Mango',
        'Energy (Kcal)': 48.35,
        'CHO (gm)': 9.79,
        'Protein (gm)': 0.55,
        'Total Fat (gm)': 0.54,
        'Total  Fiber (gm)': 1.8,
        'Glycemic Index': '51±5',
        img: 'mango.png',
      },
      {
        Name: 'Pineapple',
        'Energy (Kcal)': 43.02,
        'CHO (gm)': 9.42,
        'Protein (gm)': 0,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 3.46,
        'Glycemic Index': '59±8',
        img: 'pineapple.jpg',
      },
      {
        Name: 'Raisins,Dried Black',
        'Energy (Kcal)': 305.69,
        'CHO (gm)': 71.29,
        'Protein (gm)': 2.57,
        'Total Fat (gm)': 'Nil',
        'Total  Fiber (gm)': 3.92,
        'Glycemic Index': 'Nil',
        img: 'raisins,driedblack.png',
      },
      {
        Name: 'Raisins,Dried Golden',
        'Energy (Kcal)': 296.61,
        'CHO (gm)': 68.79,
        'Protein (gm)': 2.76,
        'Total Fat (gm)': 'Nil',
        'Total  Fiber (gm)': 4.56,
        'Glycemic Index': 'Nil',
        img: 'raisins,driedgolden.jpg',
      },
    ],
    'Roots and Tubers': [
      {
        Name: 'Beetroot',
        'Energy (Kcal)': 35.61,
        'CHO (gm)': 6.18,
        'Protein (gm)': 1.95,
        'Total Fat (gm)': 0.14,
        'Total  Fiber (gm)': 3.31,
        'Glycemic Index': 64,
        img: 'beetroot.jpg',
      },
      {
        Name: 'Potatoes',
        'Energy (Kcal)': 69.79,
        'CHO (gm)': 14.89,
        'Protein (gm)': 1.54,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 1.71,
        'Glycemic Index': '78±4',
        img: 'potatoes.jpg',
      },
      {
        Name: 'Sweet Potatoes',
        'Energy (Kcal)': 108.99,
        'CHO (gm)': 24.25,
        'Protein (gm)': 1.33,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 3.99,
        'Glycemic Index': 'Nil',
        img: 'sweetpotatoes.png',
      },
      {
        Name: 'Yam',
        'Energy (Kcal)': 83.41,
        'CHO (gm)': 17.65,
        'Protein (gm)': 2.18,
        'Total Fat (gm)': 0.17,
        'Total  Fiber (gm)': 4.08,
        'Glycemic Index': 'Nil',
        img: 'yam.png',
      },
      {
        Name: 'Tapioca ',
        'Energy (Kcal)': 79.83,
        'CHO (gm)': 17.81,
        'Protein (gm)': 1.03,
        'Total Fat (gm)': 25.89,
        'Total  Fiber (gm)': 4.61,
        'Glycemic Index': 'Nil',
        img: 'tapioca.png',
      },
    ],
    'Fish, Egg, Poultry and Meat': [
      {
        Name: 'Country Hen, Breast,with skin',
        'Energy (Kcal)': 179.97,
        'CHO (gm)': 0,
        'Protein (gm)': 22.08,
        'Total Fat (gm)': 10.2,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'countryhen,breast,withskin.png',
      },
      {
        Name: 'Country Hen, Leg,with skin',
        'Energy (Kcal)': 172.8,
        'CHO (gm)': 0,
        'Protein (gm)': 17.01,
        'Total Fat (gm)': 11.73,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'countryhen,leg,withskin.png',
      },
      {
        Name: 'Country Hen, Thigh,with skin',
        'Energy (Kcal)': 187.62,
        'CHO (gm)': 0,
        'Protein (gm)': 18.29,
        'Total Fat (gm)': 12.82,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'countryhen,thigh,withskin.png',
      },
      {
        Name: 'Country Hen, Wing,with skin',
        'Energy (Kcal)': 182.6,
        'CHO (gm)': 0,
        'Protein (gm)': 18.65,
        'Total Fat (gm)': 12.09,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'countryhen,wing,withskin.png',
      },
      {
        Name: 'Goat Liver',
        'Energy (Kcal)': 125.72,
        'CHO (gm)': 0,
        'Protein (gm)': 20.32,
        'Total Fat (gm)': 4.88,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'goatliver.jpg',
      },
    ],
    'Nuts and Oil Seeds': [
      {
        Name: 'Cashew nuts',
        'Energy (Kcal)': 582.7,
        'CHO (gm)': 25.46,
        'Protein (gm)': 18.78,
        'Total Fat (gm)': 45.2,
        'Total  Fiber (gm)': 3.86,
        'Glycemic Index': 25,
        img: 'cashewnuts.jpg',
      },
      {
        Name: 'Pistchio nuts',
        'Energy (Kcal)': 539.44,
        'CHO (gm)': 15.82,
        'Protein (gm)': 23.35,
        'Total Fat (gm)': 42.49,
        'Total  Fiber (gm)': 10.64,
        'Glycemic Index': 'Nil',
        img: 'pistacho.jpg',
      },
    ],
    'Fats and Oils': [
      {
        Name: 'Canola oil',
        'Energy (Kcal)': 884,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'canolaoil.png',
      },
      {
        Name: 'Corn oil',
        'Energy (Kcal)': 900,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 100,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'cornoil.png',
      },
      {
        Name: 'Margarine',
        'Energy (Kcal)': 717,
        'CHO (gm)': 0.7,
        'Protein (gm)': 0.16,
        'Total Fat (gm)': 80.71,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'margarine.png',
      },
    ],
    'Simple Sugars': [
      {
        Name: 'Honey',
        'Energy (Kcal)': 319,
        'CHO (gm)': 79.5,
        'Protein (gm)': 0.3,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': '61±3',
        img: 'honey.jpg',
      },
      {
        Name: 'White sugar',
        'Energy (Kcal)': 401,
        'CHO (gm)': 99.6,
        'Protein (gm)': 0,
        'Total Fat (gm)': 0.32,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'whitesugar.jpg',
      },
      {
        Name: 'Brown sugar',
        'Energy (Kcal)': 380,
        'CHO (gm)': 98.09,
        'Protein (gm)': 0.12,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'brownsugar.jpg',
      },
      {
        Name: 'Jaggery ',
        'Energy (Kcal)': 367,
        'CHO (gm)': 88.67,
        'Protein (gm)': 0,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'jaggery.jpg',
      },
      {
        Name: 'Sugar syrup',
        'Energy (Kcal)': 224.54,
        'CHO (gm)': 55.77,
        'Protein (gm)': 0,
        'Total Fat (gm)': 0.18,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 103,
        img: 'sugarsyrup.jpg',
      },
    ],
    Bakery: [
      {
        Name: 'Sweets,Cakes and Pasteries',
        'Energy (Kcal)': '200 to 800',
        'CHO (gm)': '55 to 60',
        'Protein (gm)': '6 to 10',
        'Total Fat (gm)': '15 to 25',
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'sweets,cakesandpasteries.png',
      },
      {
        Name: 'Chocolates',
        'Energy (Kcal)': 546,
        'CHO (gm)': 61,
        'Protein (gm)': 4.9,
        'Total Fat (gm)': 31,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'chocolate.jpg',
      },
      {
        Name: 'Jams',
        'Energy (Kcal)': 278,
        'CHO (gm)': 68.86,
        'Protein (gm)': 0.37,
        'Total Fat (gm)': 0.07,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'jam.jpg',
      },
      {
        Name: 'Jellies',
        'Energy (Kcal)': 266,
        'CHO (gm)': 69.95,
        'Protein (gm)': 0.15,
        'Total Fat (gm)': 0.02,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'jellies.jpg',
      },
    ],
    Beverages: [
      {
        Name: 'Sweetened Juices ',
        'Energy (Kcal)': '100 to 200',
        'CHO (gm)': '4 to 20',
        'Protein (gm)': '0.3 to 1',
        'Total Fat (gm)': '0.10 to 1',
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'sweetenedjuices.jpg',
      },
      {
        Name: 'Soft Drinks',
        'Energy (Kcal)': 42,
        'CHO (gm)': 10.36,
        'Protein (gm)': 0,
        'Total Fat (gm)': 0.25,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': '59±3',
        img: 'softdrinks.jpg',
      },
      {
        Name: 'Alcohol',
        'Energy (Kcal)': 295,
        'CHO (gm)': 0,
        'Protein (gm)': 0,
        'Total Fat (gm)': 0,
        'Total  Fiber (gm)': 0,
        'Glycemic Index': 'Nil',
        img: 'alcohol.jpg',
      },
    ],
  },
};
export default DChart;
